In [ ]:
!pip install openai-whisper

Collecting openai-whisper
  Downloading openai_whisper-20250625.tar.gz (803 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 16.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: more-itertools in /usr/local/lib/python3.11/dist-packages (from openai-whisper) (10.7.0)
Requirement already satisfied: numba in /usr/local/lib/python3.11/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from openai-whisper) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.11/dist-packages (from openai-whisper) (0.9.0)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (from openai-whisper) (2.6.0+cu124)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from openai-whisper) (4.67.1)
Requirement already satisfied: triton>=2 in /usr/local/lib/python3.11/dist-packages (from openai-whisper) (3.2.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.11/dist-packages (from tiktoken->openai-whisper) (2024.11.6)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.11/dist-packages (from tiktoken->openai-whisper) (2.32.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (4.14.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch->openai-whisper)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch->openai-whisper)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch->openai-whisper)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch->openai-whisper)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch->openai-whisper)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch->openai-whisper)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch->openai-whisper)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch->openai-whisper)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch->openai-whisper)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch->openai-whisper)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch->openai-whisper) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch->openai-whisper) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2025.7.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch->openai-whisper) (3.0.2)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 5.3 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 73.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 61.7 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 47.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.8 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.3 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 7.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 87.0 MB/s eta 0:00:00
Building wheels for collected packages: openai-whisper
  Building wheel for openai-whisper (pyproject.toml) ... done
  Created wheel for openai-whisper: filename=openai_whisper-20250625-py3-none-any.whl size=803979 sha256=94a5e14c941579c56a4b56138a3e6f8e63bd01b580ac14ad7302255a00c99213
  Stored in directory: /root/.cache/pip/wheels/32/d2/9a/801b5cc5b2a1af2e280089b71c326711a682fc1d50ea29d0ed
Successfully built openai-whisper
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, openai-whisper
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 openai-whisper-20250625

In [ ]:
!nvidia-smi

Thu Jul 17 16:35:03 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
video_url = input()

https://youtu.be/l0FvnARfGKg?si=fg3wM3vdunhYBpEj

In [ ]:
!pip install -q yt-dlp
!apt-get install -y ffmpeg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.3/174.3 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 63.7 MB/s eta 0:00:00
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.

In [ ]:
import yt_dlp

def download_and_get_title(url):
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': 'videoplayback.%(ext)s',  # save using title as filename
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)  # downloads + returns metadata
        title = info.get('title', 'unknown_title')
        print(f"Downloaded: {title}.mp3")
        return title

In [ ]:
title = download_and_get_title(video_url)

[youtube] Extracting URL: https://youtu.be/l0FvnARfGKg?si=fg3wM3vdunhYBpEj
[youtube] l0FvnARfGKg: Downloading webpage
[youtube] l0FvnARfGKg: Downloading tv client config
[youtube] l0FvnARfGKg: Downloading player 69b31e11-main
[youtube] l0FvnARfGKg: Downloading tv player API JSON
[youtube] l0FvnARfGKg: Downloading ios player API JSON
[youtube] l0FvnARfGKg: Downloading m3u8 information
[info] l0FvnARfGKg: Downloading 1 format(s): 251
[download] Destination: videoplayback.webm
[download] 100% of    5.78MiB in 00:00:00 at 10.86MiB/s
[ExtractAudio] Destination: videoplayback.mp3
Deleting original file videoplayback.webm (pass -k to keep)
Downloaded: THIS Leetcode Strategy Got Me Multiple Big Tech Offers..mp3

In [ ]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda

In [ ]:
import whisper

model = whisper.load_model("small")

100%|███████████████████████████████████████| 461M/461M [00:14<00:00, 34.2MiB/s]

In [ ]:
result = model.transcribe("videoplayback.mp3")

In [ ]:
result

{'text': " I applied this exact Leak Code strategy and I was able to secure offers from Google, Amazon, Microsoft, Automall, and many more within three months of applying the strategy. Hi, my name is Messy Mungle and if you don't already know me, I'm a software engineer at Google and I created a lot of tech career advice content on Instagram, LinkedIn, and now YouTube as well. So make sure to hit the subscribe button and follow my other pages as well. So the number one thing that people get stuck on is what programming language do you use for an interview? Now usually programming languages don't matter, especially for fan companies. So unless you're applying for a specific role that requires you to interview in a specific language, choose whatever language that you are comfortable using. Now I say this with a little grain of salt because I actually failed one of my interviews because I was using C++ and I know this language executes faster than most other languages. However, I got rejected just because of the sheer amount of lines of code I had to write which could have been done in basically five to 10 lines of code if I was to use Python. So really what matters is the speed of which you program in and how quickly you're able to solve the problem. So my advice for you when you're choosing a programming language is actually to first look at that question. If it's a string related question where you have to take an input from the stream and then output it, etc, etc, just use the language like Python. It's much faster than using a language like C++ which requires you to add additional lines of code just to process that data. But generally speaking, choosing a programming language does not matter. Next let's talk about time complexity and space complexity. I do not care what phase of engineering you're in. If you're an intern, if you're looking for a new grad, if you're looking for senior engineering roles, time and space complexity is going to be asked. You should really know all of your own notations. It's actually this chart that I always use before going into any interview. You should always be able to look at your code and figure out what the space and time complexity of your algorithm is. This is definitely definitely going to be asked if you're an intern or a new grad, but even for senior engineering roles, sometimes it's asked. Now before I dive into the exact lead code strategy that I took, I want to talk about DSA fundamentals. If you don't know your DSA fundamentals, you're not going to be efficient with lead code. In fact, many of the interviews that I've taken in the past have asked me the most basic question that I learned back in like second year of college. For example, one of my interview questions in a top company was to implement a hash map and another one was to implement LRU cache. So this is why I say to make sure that you know your DSA fundamentals because you don't know when these questions could be asked. And the other thing is if you know your fundamentals very well, then you're going to be able to choose the correct data structure or algorithm that's required in order to solve a lead code problem. Now let's finally move on to the exact lead code strategy I used in order to crack all these fake companies. Number one, I suggest you get lead code premium or at least the CTC I've bought. I don't think lead code premium is required when you're just starting off, but if you're within one to two month mark of your interviews, I highly recommend getting the lead code premium so that you can solve the most frequently asked company questions. And I truly think that CTC I book is very good to have just again to brush over your fundamentals and kind of review the answers and how you go about thinking them in the first place. Now the exact strategy that I took is that number one, you want to go over arrays, link list and maps. Now obviously, first of all, you want to make sure that you understand what these data structures are and exactly why you use them. So it doesn't exactly matter how many questions you do for each of these categories, but you need to be able to figure out what wording each of these questions are using that kind of direct you to a specific data structure or algorithm. So after you do arrays, link list and map, I would move on to searching algorithms, sorting algorithms and trees. When you're an intern, most of the questions you're going to be asked is going to be within these first two categories. So you want to make sure that you're super, super good at these. You want to know your pre in and post-order traversals for the binary trees. And then for the searching and sorting algorithms, you want to know how to implement them, especially your binary search, linear search and quick sorts. And also again, know the time complexity and space complexity of these algorithms, especially when you apply them in a problem. Now moving on after you've done a couple of questions in these categories, you want to do one through 50 on link code in order. I think these questions give you a pretty good understanding of how to apply these algorithms as well as data structures before moving on to the more complex ones. Now the second part of this roadmap is really for your new grads and senior engineering roles. You're most likely not going to be asked link list type of questions, but still make sure that you know about these. Instead, what you want to focus on is graphs, backtracking algorithms, recursion, heaps and priority queues, especially when you're applying to FANG. There's a lot of different sorts of problems that is going to use at least one, if not two of these different data structures and algorithms. And these questions can be complex. So you really want to make sure that you know how to combine these things together. And if you do blind 75 or blind 150 next, depending on how much time you have, I think you're going to have a solid basic understanding of what these bigger companies require. What you want to focus on next is DP, tries and union sets. I know DP is everyone's favorite and I know it's very difficult. So most of the time you're probably not going to be asked DP problems, but you never know. So you want to at least practice 20, 30 questions of these before kind of giving up. I think tries and union sets are very good structures to know as well. Once you kind of say that to an interviewer, they're going to be very impressed that you thought of these data structures. So it's going to give you brownie points, but these are definitely the structures and algorithms that you want to learn at the very end when you're already good at your medium and hard level problems. Now finally, I want to address what to do when you're stuck in the middle of a tech interview. Obviously, the first thing is make sure you're getting the brute force solution out. But while you're doing that, make sure that you're thinking of what other data structure algorithm you can use to make your solution better. Cause that's a hundred percent going to be the follow up question. If you have time left. Second thing is make sure you're asking your clarification questions upfront and kind of making sure that you and your interviewer are on the same page. You don't want to be going down the wrong path and figure out that you're on the wrong path 20 to 30 minutes later in your interview. So really ask upfront, does this make sense to you? And if you're genuinely stuck in the interview, just ask for a hint. I think the worst thing for an interviewer is if you give up on a problem. Remember that an interviewer has been in the same exact seat that you are in currently. So really they want to try to help you. It's just that you need to ask for it and ask for it correctly. The interviewer is just trying to make sure that you're a person that they can work with. They're not trying to reject you. If you liked this video, then make sure to give it a thumbs up and make sure to subscribe to my channel below. Let me help you achieve your tech career dreams.",
 'segments': [{'id': 0,
   'seek': 0,
   'start': 0.0,
   'end': 4.84,
   'text': ' I applied this exact Leak Code strategy and I was able to secure offers from Google, Amazon,',
   'tokens': [50364,
    286,
    6456,
    341,
    1900,
    1456,
    514,
    15549,
    5206,
    293,
    286,
    390,
    1075,
    281,
    7144,
    7736,
    490,
    3329,
    11,
    6795,
    11,
    50606],
   'temperature': 0.0,
   'avg_logprob': -0.21245742566657788,
   'compression_ratio': 1.605421686746988,
   'no_speech_prob': 0.0021484806202352047},
  {'id': 1,
   'seek': 0,
   'start': 4.84,
   'end': 9.52,
   'text': ' Microsoft, Automall, and many more within three months of applying the strategy.',
   'tokens': [50606,
    8116,
    11,
    24619,
    336,
    11,
    293,
    867,
    544,
    1951,
    1045,
    2493,
    295,
    9275,
    264,
    5206,
    13,
    50840],
   'temperature': 0.0,
   'avg_logprob': -0.21245742566657788,
   'compression_ratio': 1.605421686746988,
   'no_speech_prob': 0.0021484806202352047},
  {'id': 2,
   'seek': 0,
   'start': 9.52,
   'end': 13.34,
   'text': " Hi, my name is Messy Mungle and if you don't already know me, I'm a software engineer at",
   'tokens': [50840,
    2421,
    11,
    452,
    1315,
    307,
    9847,
    88,
    376,
    1063,
    306,
    293,
    498,
    291,
    500,
    380,
    1217,
    458,
    385,
    11,
    286,
    478,
    257,
    4722,
    11403,
    412,
    51031],
   'temperature': 0.0,
   'avg_logprob': -0.21245742566657788,
   'compression_ratio': 1.605421686746988,
   'no_speech_prob': 0.0021484806202352047},
  {'id': 3,
   'seek': 0,
   'start': 13.34,
   'end': 18.56,
   'text': ' Google and I created a lot of tech career advice content on Instagram, LinkedIn, and',
   'tokens': [51031,
    3329,
    293,
    286,
    2942,
    257,
    688,
    295,
    7553,
    3988,
    5192,
    2701,
    322,
    5281,
    11,
    20657,
    11,
    293,
    51292],
   'temperature': 0.0,
   'avg_logprob': -0.21245742566657788,
   'compression_ratio': 1.605421686746988,
   'no_speech_prob': 0.0021484806202352047},
  {'id': 4,
   'seek': 0,
   'start': 18.56,
   'end': 19.68,
   'text': ' now YouTube as well.',
   'tokens': [51292, 586, 3088, 382, 731, 13, 51348],
   'temperature': 0.0,
   'avg_logprob': -0.21245742566657788,
   'compression_ratio': 1.605421686746988,
   'no_speech_prob': 0.0021484806202352047},
  {'id': 5,
   'seek': 0,
   'start': 19.68,
   'end': 23.52,
   'text': ' So make sure to hit the subscribe button and follow my other pages as well.',
   'tokens': [51348,
    407,
    652,
    988,
    281,
    2045,
    264,
    3022,
    2960,
    293,
    1524,
    452,
    661,
    7183,
    382,
    731,
    13,
    51540],
   'temperature': 0.0,
   'avg_logprob': -0.21245742566657788,
   'compression_ratio': 1.605421686746988,
   'no_speech_prob': 0.0021484806202352047},
  {'id': 6,
   'seek': 0,
   'start': 23.52,
   'end': 29.12,
   'text': ' So the number one thing that people get stuck on is what programming language do you use',
   'tokens': [51540,
    407,
    264,
    1230,
    472,
    551,
    300,
    561,
    483,
    5541,
    322,
    307,
    437,
    9410,
    2856,
    360,
    291,
    764,
    51820],
   'temperature': 0.0,
   'avg_logprob': -0.21245742566657788,
   'compression_ratio': 1.605421686746988,
   'no_speech_prob': 0.0021484806202352047},
  {'id': 7,
   'seek': 2912,
   'start': 29.12,
   'end': 30.12,
   'text': ' for an interview?',
   'tokens': [50364, 337, 364, 4049, 30, 50414],
   'temperature': 0.0,
   'avg_logprob': -0.16908001695942676,
   'compression_ratio': 1.7525083612040133,
   'no_speech_prob': 0.03620551526546478},
  {'id': 8,
   'seek': 2912,
   'start': 30.12,
   'end': 34.32,
   'text': " Now usually programming languages don't matter, especially for fan companies.",
   'tokens': [50414,
    823,
    2673,
    9410,
    8650,
    500,
    380,
    1871,
    11,
    2318,
    337,
    3429,
    3431,
    13,
    50624],
   'temperature': 0.0,
   'avg_logprob': -0.16908001695942676,
   'compression_ratio': 1.7525083612040133,
   'no_speech_prob': 0.03620551526546478},
  {'id': 9,
   'seek': 2912,
   'start': 34.32,
   'end': 38.72,
   'text': " So unless you're applying for a specific role that requires you to interview in a specific",
   'tokens': [50624,
    407,
    5969,
    291,
    434,
    9275,
    337,
    257,
    2685,
    3090,
    300,
    7029,
    291,
    281,
    4049,
    294,
    257,
    2685,
    50844],
   'temperature': 0.0,
   'avg_logprob': -0.16908001695942676,
   'compression_ratio': 1.7525083612040133,
   'no_speech_prob': 0.03620551526546478},
  {'id': 10,
   'seek': 2912,
   'start': 38.72,
   'end': 42.24,
   'text': ' language, choose whatever language that you are comfortable using.',
   'tokens': [50844,
    2856,
    11,
    2826,
    2035,
    2856,
    300,
    291,
    366,
    4619,
    1228,
    13,
    51020],
   'temperature': 0.0,
   'avg_logprob': -0.16908001695942676,
   'compression_ratio': 1.7525083612040133,
   'no_speech_prob': 0.03620551526546478},
  {'id': 11,
   'seek': 2912,
   'start': 42.24,
   'end': 46.96,
   'text': ' Now I say this with a little grain of salt because I actually failed one of my interviews',
   'tokens': [51020,
    823,
    286,
    584,
    341,
    365,
    257,
    707,
    12837,
    295,
    5139,
    570,
    286,
    767,
    7612,
    472,
    295,
    452,
    12318,
    51256],
   'temperature': 0.0,
   'avg_logprob': -0.16908001695942676,
   'compression_ratio': 1.7525083612040133,
   'no_speech_prob': 0.03620551526546478},
  {'id': 12,
   'seek': 2912,
   'start': 46.96,
   'end': 52.84,
   'text': ' because I was using C++ and I know this language executes faster than most other languages.',
   'tokens': [51256,
    570,
    286,
    390,
    1228,
    383,
    25472,
    293,
    286,
    458,
    341,
    2856,
    4454,
    1819,
    4663,
    813,
    881,
    661,
    8650,
    13,
    51550],
   'temperature': 0.0,
   'avg_logprob': -0.16908001695942676,
   'compression_ratio': 1.7525083612040133,
   'no_speech_prob': 0.03620551526546478},
  {'id': 13,
   'seek': 2912,
   'start': 52.84,
   'end': 57.760000000000005,
   'text': ' However, I got rejected just because of the sheer amount of lines of code I had to write',
   'tokens': [51550,
    2908,
    11,
    286,
    658,
    15749,
    445,
    570,
    295,
    264,
    23061,
    2372,
    295,
    3876,
    295,
    3089,
    286,
    632,
    281,
    2464,
    51796],
   'temperature': 0.0,
   'avg_logprob': -0.16908001695942676,
   'compression_ratio': 1.7525083612040133,
   'no_speech_prob': 0.03620551526546478},
  {'id': 14,
   'seek': 5776,
   'start': 57.879999999999995,
   'end': 62.96,
   'text': ' which could have been done in basically five to 10 lines of code if I was to use Python.',
   'tokens': [50370,
    597,
    727,
    362,
    668,
    1096,
    294,
    1936,
    1732,
    281,
    1266,
    3876,
    295,
    3089,
    498,
    286,
    390,
    281,
    764,
    15329,
    13,
    50624],
   'temperature': 0.0,
   'avg_logprob': -0.11978841460911574,
   'compression_ratio': 1.6691176470588236,
   'no_speech_prob': 0.12246483564376831},
  {'id': 15,
   'seek': 5776,
   'start': 62.96,
   'end': 68.03999999999999,
   'text': " So really what matters is the speed of which you program in and how quickly you're able",
   'tokens': [50624,
    407,
    534,
    437,
    7001,
    307,
    264,
    3073,
    295,
    597,
    291,
    1461,
    294,
    293,
    577,
    2661,
    291,
    434,
    1075,
    50878],
   'temperature': 0.0,
   'avg_logprob': -0.11978841460911574,
   'compression_ratio': 1.6691176470588236,
   'no_speech_prob': 0.12246483564376831},
  {'id': 16,
   'seek': 5776,
   'start': 68.03999999999999,
   'end': 69.56,
   'text': ' to solve the problem.',
   'tokens': [50878, 281, 5039, 264, 1154, 13, 50954],
   'temperature': 0.0,
   'avg_logprob': -0.11978841460911574,
   'compression_ratio': 1.6691176470588236,
   'no_speech_prob': 0.12246483564376831},
  {'id': 17,
   'seek': 5776,
   'start': 69.56,
   'end': 73.36,
   'text': " So my advice for you when you're choosing a programming language is actually to first",
   'tokens': [50954,
    407,
    452,
    5192,
    337,
    291,
    562,
    291,
    434,
    10875,
    257,
    9410,
    2856,
    307,
    767,
    281,
    700,
    51144],
   'temperature': 0.0,
   'avg_logprob': -0.11978841460911574,
   'compression_ratio': 1.6691176470588236,
   'no_speech_prob': 0.12246483564376831},
  {'id': 18,
   'seek': 5776,
   'start': 73.36,
   'end': 74.52,
   'text': ' look at that question.',
   'tokens': [51144, 574, 412, 300, 1168, 13, 51202],
   'temperature': 0.0,
   'avg_logprob': -0.11978841460911574,
   'compression_ratio': 1.6691176470588236,
   'no_speech_prob': 0.12246483564376831},
  {'id': 19,
   'seek': 5776,
   'start': 74.52,
   'end': 79.16,
   'text': " If it's a string related question where you have to take an input from the stream and",
   'tokens': [51202,
    759,
    309,
    311,
    257,
    6798,
    4077,
    1168,
    689,
    291,
    362,
    281,
    747,
    364,
    4846,
    490,
    264,
    4309,
    293,
    51434],
   'temperature': 0.0,
   'avg_logprob': -0.11978841460911574,
   'compression_ratio': 1.6691176470588236,
   'no_speech_prob': 0.12246483564376831},
  {'id': 20,
   'seek': 5776,
   'start': 79.16,
   'end': 83.03999999999999,
   'text': ' then output it, etc, etc, just use the language like Python.',
   'tokens': [51434,
    550,
    5598,
    309,
    11,
    5183,
    11,
    5183,
    11,
    445,
    764,
    264,
    2856,
    411,
    15329,
    13,
    51628],
   'temperature': 0.0,
   'avg_logprob': -0.11978841460911574,
   'compression_ratio': 1.6691176470588236,
   'no_speech_prob': 0.12246483564376831},
  {'id': 21,
   'seek': 8304,
   'start': 83.04,
   'end': 88.0,
   'text': " It's much faster than using a language like C++ which requires you to add additional lines",
   'tokens': [50364,
    467,
    311,
    709,
    4663,
    813,
    1228,
    257,
    2856,
    411,
    383,
    25472,
    597,
    7029,
    291,
    281,
    909,
    4497,
    3876,
    50612],
   'temperature': 0.0,
   'avg_logprob': -0.12507920111379317,
   'compression_ratio': 1.7525773195876289,
   'no_speech_prob': 0.06559359282255173},
  {'id': 22,
   'seek': 8304,
   'start': 88.0,
   'end': 90.64,
   'text': ' of code just to process that data.',
   'tokens': [50612, 295, 3089, 445, 281, 1399, 300, 1412, 13, 50744],
   'temperature': 0.0,
   'avg_logprob': -0.12507920111379317,
   'compression_ratio': 1.7525773195876289,
   'no_speech_prob': 0.06559359282255173},
  {'id': 23,
   'seek': 8304,
   'start': 90.64,
   'end': 94.64,
   'text': ' But generally speaking, choosing a programming language does not matter.',
   'tokens': [50744,
    583,
    5101,
    4124,
    11,
    10875,
    257,
    9410,
    2856,
    775,
    406,
    1871,
    13,
    50944],
   'temperature': 0.0,
   'avg_logprob': -0.12507920111379317,
   'compression_ratio': 1.7525773195876289,
   'no_speech_prob': 0.06559359282255173},
  {'id': 24,
   'seek': 8304,
   'start': 94.64,
   'end': 97.72,
   'text': " Next let's talk about time complexity and space complexity.",
   'tokens': [50944,
    3087,
    718,
    311,
    751,
    466,
    565,
    14024,
    293,
    1901,
    14024,
    13,
    51098],
   'temperature': 0.0,
   'avg_logprob': -0.12507920111379317,
   'compression_ratio': 1.7525773195876289,
   'no_speech_prob': 0.06559359282255173},
  {'id': 25,
   'seek': 8304,
   'start': 97.72,
   'end': 101.12,
   'text': " I do not care what phase of engineering you're in.",
   'tokens': [51098,
    286,
    360,
    406,
    1127,
    437,
    5574,
    295,
    7043,

In [ ]:
transcript_data = []
for segment in result['segments']:
  transcript_data.append({
      'id' : segment['id'],
      'start' : round(segment['start'],2),
      'end' : round(segment['end'],2),
      'text' : segment['text']
  })

In [ ]:
import pandas as pd
transcript_data = pd.DataFrame(transcript_data)

In [ ]:
transcript_data.head()

   id  start    end                                               text
0   0   0.00   4.84   I applied this exact Leak Code strategy and I...
1   1   4.84   9.52   Microsoft, Automall, and many more within thr...
2   2   9.52  13.34   Hi, my name is Messy Mungle and if you don't ...
3   3  13.34  18.56   Google and I created a lot of tech career adv...
4   4  18.56  19.68                               now YouTube as well.

In [ ]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.53.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.7.14)

# ***PREPROCESSING OF DATA***

In [ ]:
!pip install spacy

Requirement already satisfied: spacy in /usr/local/lib/python3.11/dist-packages (3.8.7)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.11/dist-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (0.16.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.11.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.7.14)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.21.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.3.0.post1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
import re

In [ ]:


filler_words = {
    "um", "uh", "hmm", "erm", "er", "ah", "oh", "like", "you know",
    "i mean", "sort of", "kind of", "actually", "basically",
    "literally", "right", "okay", "well", "so", "just", "you see",
    "you know what I mean", "you get me", "you feel me", "let's see",
    "I guess", "alright", "kinda", "yeah", "mmm", "I suppose"
}
filler_phrases = []
for word in filler_words:
  filler_phrases.append(r"\b"+ re.escape(word) + r"\b")

functions for text preprocessing

In [ ]:
def remove_adj(text):
  doc = nlp(text)
  keep = []
  for token in doc:
    if token.pos_ == "INTJ":
      continue
    if token.lower_ in {"like","literally","basically"}:
      continue
    keep.append(token.text_with_ws)

  return " ".join(keep)

In [ ]:
def remove_fillers(text):
  for pattern in filler_phrases:
      text = re.sub(pattern,"",text,flags=re.IGNORECASE)
  return text.strip()

In [ ]:
transcript_data['text'] = transcript_data['text'].apply(remove_fillers)
transcript_data['text'] = transcript_data['text'].apply(remove_adj)

In [ ]:
transcript_data

      id   start     end                                               text
0      0    0.00    4.84  I  applied  this  exact  Leak  Code  strategy ...
1      1    4.84    9.52  Microsoft ,  Automall ,  and  many  more  with...
2      2    9.52   13.34  ,  my  name  is  Messy  Mungle  and  if  you  ...
3      3   13.34   18.56  Google  and  I  created  a  lot  of  tech  car...
4      4   18.56   19.68                                now  YouTube  as  .
..   ...     ...     ...                                                ...
118  118  423.28  426.92  If  you  liked  this  video ,  then  make  sur...
119  119  426.92  428.20                           to  my  channel  below .
120  120  428.20  430.40  Let  me  help  you  achieve  your  tech  caree...
121  121  428.20  430.40                                  ahaaa  i  got  it
122  122  428.20  430.40                                          it  hurts

[123 rows x 4 columns]

## ***ANALYSIS OF DATA***

In [ ]:
from transformers import AutoTokenizer

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("intfloat/e5-base-v2")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [ ]:
transcript_data['text-count'] = transcript_data['text'].apply(lambda x: len(x.split()))
transcript_data['token-count'] = transcript_data['text'].apply(
    lambda x: len(tokenizer.encode(x, add_special_tokens=False))
)

In [ ]:
transcript_data.describe().round(2)

           id   start     end  text-count  token-count
count  123.00  123.00  123.00      123.00       123.00
mean    61.00  223.96  227.49       13.24        14.16
std     35.65  126.66  126.43        5.49         6.11
min      0.00    0.00    4.84        2.00         2.00
25%     30.50  118.26  121.16       10.00        10.00
50%     61.00  224.84  228.92       15.00        16.00
75%     91.50  333.04  338.68       18.00        19.00
max    122.00  428.20  430.40       21.00        26.00

# ***chunking***

In [ ]:
i = 0
index = 0
MAX_TOKENS = 350
transcript_data_after_chunking_together = []

while index < len(transcript_data):
    sum_tokens = 0
    new_text = ""
    start_time = transcript_data.iloc[index]['start']
    end_time = None

    chunk_texts = []

    while index < len(transcript_data) and sum_tokens + transcript_data.iloc[index]['token-count'] <= MAX_TOKENS:
        sum_tokens += transcript_data.iloc[index]['token-count']
        chunk_texts.append(transcript_data.iloc[index]['text'].strip())
        end_time = transcript_data.iloc[index]['end']
        index += 1

    new_text = " ".join(chunk_texts)


    transcript_data_after_chunking_together.append({
        'id': i,
        'start': start_time,
        'end': end_time,
        'text': new_text
    })
    i += 1

In [ ]:
transcript_data_after_chunking_together

[{'id': 0,
  'start': np.float64(0.0),
  'end': np.float64(94.64),
  'text': "I  applied  this  exact  Leak  Code  strategy  and  I  was  able  to  secure  offers  from  Google ,  Amazon , Microsoft ,  Automall ,  and  many  more  within  three  months  of  applying  the  strategy . ,  my  name  is  Messy  Mungle  and  if  you  do n't  already  know  me ,  I 'm  a  software  engineer  at Google  and  I  created  a  lot  of  tech  career  advice  content  on  Instagram ,  LinkedIn ,  and now  YouTube  as  . make  sure  to  hit  the  subscribe  button  and  follow  my  other  pages  as  . the  number  one  thing  that  people  get  stuck  on  is  what  programming  language  do  you  use for  an  interview ? Now  usually  programming  languages  do n't  matter ,  especially  for  fan  companies . unless  you 're  applying  for  a  specific  role  that  requires  you  to  interview  in  a  specific language ,  choose  whatever  language  that  you  are  comfortable  using . Now  I  say  this  with  a  little  grain  of  salt  because  I    failed  one  of  my  interviews because  I  was  using  C++  and  I  know  this  language  executes  faster  than  most  other  languages . However ,  I  got  rejected    because  of  the  sheer  amount  of  lines  of  code  I  had  to  write which  could  have  been  done  in    five  to  10  lines  of  code  if  I  was  to  use  Python . really  what  matters  is  the  speed  of  which  you  program  in  and  how  quickly  you 're  able to  solve  the  problem . my  advice  for  you  when  you 're  choosing  a  programming  language  is    to  first look  at  that  question . If  it 's  a  string  related  question  where  you  have  to  take  an  input  from  the  stream  and then  output  it ,  etc ,  etc ,    use  the  language    Python . It 's  much  faster  than  using  a  language    C++  which  requires  you  to  add  additional  lines of  code    to  process  that  data . But  generally  speaking ,  choosing  a  programming  language  does  not  matter ."},
 {'id': 1,
  'start': np.float64(94.64),
  'end': np.float64(181.12),
  'text': "Next  let 's  talk  about  time  complexity  and  space  complexity . I  do  not  care  what  phase  of  engineering  you 're  in . If  you 're  an  intern ,  if  you 're  looking  for  a  new  grad ,  if  you 're  looking  for  senior engineering  roles ,  time  and  space  complexity  is  going  to  be  asked . You  should  really  know  all  of  your  own  notations . It 's    this  chart  that  I  always  use  before  going  into  any  interview . You  should  always  be  able  to  look  at  your  code  and  figure  out  what  the  space  and  time complexity  of  your  algorithm  is . This  is  definitely  definitely  going  to  be  asked  if  you 're  an  intern  or  a  new  grad ,  but even  for  senior  engineering  roles ,  sometimes  it 's  asked . Now  before  I  dive  into  the  exact  lead  code  strategy  that  I  took ,  I  want  to  talk  about DSA  fundamentals . If  you  do n't  know  your  DSA  fundamentals ,  you 're  not  going  to  be  efficient  with  lead code . In  fact ,  many  of  the  interviews  that  I 've  taken  in  the  past  have  asked  me  the  most  basic question  that  I  learned  back  in    second  year  of  college . For  example ,  one  of  my  interview  questions  in  a  top  company  was  to  implement  a  hash map  and  another  one  was  to  implement  LRU  cache . this  is  why  I  say  to  make  sure  that    your  DSA  fundamentals  because  you  do n't know  when  these  questions  could  be  asked . And  the  other  thing  is  if    your  fundamentals  very  ,  then  you 're  going  to  be  able  to choose  the  correct  data  structure  or  algorithm  that 's  required  in  order  to  solve  a  lead code  problem . let 's  finally  move  on  to  the  exact  lead  code  strategy  I  used  in  order  to  crack  all these  fake  companies ."},
 {'id': 2,
  'start': np.float64(181.12),
  'end': np.float64(266.28),
  'text': "Number  one ,  I  suggest  you  get  lead  code  premium  or  at  least  the  CTC  I 've  bought . I  do n't  think  lead  code  premium  is  required  when  you 're    starting  off ,  but  if  you 're within  one  to  two  month  mark  of  your  interviews ,  I  highly  recommend  getting  the  lead  code  premium that  you  can  solve  the  most  frequently  asked  company  questions . And  I  truly  think  that  CTC  I  book  is  very  good  to  have    again  to  brush  over  your fundamentals  and    review  the  answers  and  how  you  go  about  thinking  them  in  the first  place . Now  the  exact  strategy  that  I  took  is  that  number  one ,  you  want  to  go  over  arrays ,  link list  and  maps . Now  obviously ,  first  of  all ,  you  want  to  make  sure  that  you  understand  what  these  data  structures are  and  exactly  why  you  use  them . it  does n't  exactly  matter  how  many  questions  you  do  for  each  of  these  categories ,  but  you need  to  be  able  to  figure  out  what  wording  each  of  these  questions  are  using  that  kind of  direct  you  to  a  specific  data  structure  or  algorithm . after  you  do  arrays ,  link  list  and  map ,  I  would  move  on  to  searching  algorithms ,  sorting algorithms  and  trees . When  you 're  an  intern ,  most  of  the  questions  you 're  going  to  be  asked  is  going  to  be  within these  first  two  categories . you  want  to  make  sure  that  you 're  super ,  super  good  at  these . You  want  to  know  your  pre  in  and  post - order  traversals  for  the  binary  trees . And  then  for  the  searching  and  sorting  algorithms ,  you  want  to  know  how  to  implement  them ,  especially your  binary  search ,  linear  search  and  quick  sorts . And  also  again ,  know  the  time  complexity  and  space  complexity  of  these  algorithms ,  especially when  you  apply  them  in  a  problem ."},
 {'id': 3,
  'start': np.float64(266.28),
  'end': np.float64(352.04),
  'text': "Now  moving  on  after  you 've  done  a  couple  of  questions  in  these  categories ,  you  want  to do  one  through  50  on  link  code  in  order . I  think  these  questions  give  you  a  pretty  good  understanding  of  how  to  apply  these  algorithms as    as  data  structures  before  moving  on  to  the  more  complex  ones . the  second  part  of  this  roadmap  is  really  for  your  new  grads  and  senior  engineering roles . You 're  most  likely  not  going  to  be  asked  link  list  type  of  questions ,  but  still  make sure  that    about  these . Instead ,  what  you  want  to  focus  on  is  graphs ,  backtracking  algorithms ,  recursion ,  heaps and  priority  queues ,  especially  when  you 're  applying  to  FANG . There 's  a  lot  of  different  sorts  of  problems  that  is  going  to  use  at  least  one ,  if  not two  of  these  different  data  structures  and  algorithms . And  these  questions  can  be  complex . you  really  want  to  make  sure  that    how  to  combine  these  things  together . And  if  you  do  blind  75  or  blind  150  next ,  depending  on  how  much  time  you  have ,  I  think you 're  going  to  have  a  solid  basic  understanding  of  what  these  bigger  companies  require . What  you  want  to  focus  on  next  is  DP ,  tries  and  union  sets . I  know  DP  is  everyone 's  favorite  and  I  know  it 's  very  difficult . most  of  the  time  you 're  probably  not  going  to  be  asked  DP  problems ,  but  you  never  know . you  want  to  at  least  practice  20 ,  30  questions  of  these  before    giving  up . I  think  tries  and  union  sets  are  very  good  structures  to  know  as  . Once  you    say  that  to  an  interviewer ,  they 're  going  to  be  very  impressed  that  you thought  of  these  data  structures ."},
 {'id': 4,
  'start': np.float64(352.04),
  'end': np.float64(428.2),
  'text': "it 's  going  to  give  you  brownie  points ,  but  these  are  definitely  the  structures  and algorithms  that  you  want  to  learn  at  the  very  end  when  you 're  already  good  at  your  medium and  hard  level  problems . Now  finally ,  I  want  to  address  what  to  do  when  you 're  stuck  in  the  middle  of  a  tech interview . Obviously ,  the  first  thing  is  make  sure  you 're  getting  the  brute  force  solution  out . But  while  you 're  doing  that ,  make  sure  that  you 're  thinking  of  what  other  data  structure algorithm  you  can  use  to  make  your  solution  better . Cause  that 's  a  hundred  percent  going  to  be  the  follow  up  question . If  you  have  time  left . Second  thing  is  make  sure  you 're  asking  your  clarification  questions  upfront  and making  sure  that  you  and  your  interviewer  are  on  the  same  page . You  do n't  want  to  be  going  down  the  wrong  path  and  figure  out  that  you 're  on  the  wrong path  20  to  30  minutes  later  in  your  interview . really  ask  upfront ,  does  this  make  sense  to  you ? And  if  you 're  genuinely  stuck  in  the  interview ,    ask  for  a  hint . I  think  the  worst  thing  for  an  interviewer  is  if  you  give  up  on  a  problem . Remember  that  an  interviewer  has  been  in  the  same  exact  seat  that  you  are  in  currently . really  they  want  to  try  to  help  you . It 's    that  you  need  to  ask  for  it  and  ask  for  it  correctly . The  interviewer  is    trying  to  make  sure  that  you 're  a  person  that  they  can  work  with . They 're  not  trying  to  reject  you . If  you  liked  this  video ,  then  make  sure  to  give  it  a  thumbs  up  and  make  sure  to  subscribe to  my  channel  below ."},
 {'id': 5,
  'start': np.float64(428.2),
  'end': np.float64(430.4),
  'text': 'Let  me  help  you  achieve  your  tech  career  dreams . ahaaa  i  got  it it  hurts'}]

In [ ]:
transcript_data_after_chunking_together = pd.DataFrame(transcript_data_after_chunking_together)
transcript_data_after_chunking_together

   id   start     end                                               text
0   0    0.00   94.64  I  applied  this  exact  Leak  Code  strategy ...
1   1   94.64  181.12  Next  let 's  talk  about  time  complexity  a...
2   2  181.12  266.28  Number  one ,  I  suggest  you  get  lead  cod...
3   3  266.28  352.04  Now  moving  on  after  you 've  done  a  coup...
4   4  352.04  428.20  it 's  going  to  give  you  brownie  points ,...
5   5  428.20  430.40  Let  me  help  you  achieve  your  tech  caree...

In [ ]:
from sentence_transformers import SentenceTransformer
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device for SentenceTransformer model: {device}")
model = SentenceTransformer('intfloat/e5-base-v2').to(device)
print(f"SentenceTransformer model is on device: {model.device}")

Using device for SentenceTransformer model: cuda

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/650 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

SentenceTransformer model is on device: cuda:0

In [ ]:
embeddings = []

for _,element in transcript_data_after_chunking_together.iterrows():
  input_text = "passage: "+ element['text']
  print(f"Processing chunk with text: {input_text[:50]}...") # Print part of the text being processed
  embedding = model.encode(input_text,
                           batch_size = 32,
                           normalize_embeddings=True,
                           convert_to_tensor=True) # Convert to tensor here
  print(f"Embedding tensor is on device: {embedding.device}") # Print device of the embedding tensor
  embeddings.append(embedding.cpu().numpy()) # Move back to CPU and convert to numpy

transcript_data_after_chunking_together['embedding'] = embeddings

Processing chunk with text: passage: I  applied  this  exact  Leak  Code  stra...
Embedding tensor is on device: cuda:0
Processing chunk with text: passage: Next  let 's  talk  about  time  complexi...
Embedding tensor is on device: cuda:0
Processing chunk with text: passage: Number  one ,  I  suggest  you  get  lead...
Embedding tensor is on device: cuda:0
Processing chunk with text: passage: Now  moving  on  after  you 've  done  a ...
Embedding tensor is on device: cuda:0
Processing chunk with text: passage: it 's  going  to  give  you  brownie  poi...
Embedding tensor is on device: cuda:0
Processing chunk with text: passage: Let  me  help  you  achieve  your  tech  ...
Embedding tensor is on device: cuda:0

In [ ]:
transcript_data_after_chunking_together

,id,start,end,text,embedding
0,0,0.00,94.64,I applied this exact Leak Code strategy ...,"[0.048758633, -0.05580547, -0.046355322, 0.012..."
1,1,94.64,181.12,Next let 's talk about time complexity a...,"[-0.012813714, -0.0072784997, -0.053541053, -0..."
2,2,181.12,266.28,"Number one , I suggest you get lead cod...","[-0.002432627, -0.038955163, -0.023889303, -0...."
3,3,266.28,352.04,Now moving on after you 've done a coup...,"[0.010830883, -0.024413647, -0.04404242, -0.00..."
4,4,352.04,428.20,"it 's going to give you brownie points ,...","[0.004646819, -0.040356316, -0.04286418, 0.024..."
5,5,428.20,430.40,Let me help you achieve your tech caree...,"[0.00030340138, -0.014475895, -0.027766095, 0...."

# ***RAG***

In [ ]:
import torch

In [ ]:
import numpy as np
import pandas as pd

device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
dict_of_chunks = transcript_data_after_chunking_together.to_dict(orient = "records")

embeddings_torch = torch.tensor(np.array(transcript_data_after_chunking_together["embedding"].tolist()), dtype=torch.float32).to(device)

In [ ]:
embeddings_torch.shape

torch.Size([6, 768])

In [ ]:
result['text']

" I applied this exact Leak Code strategy and I was able to secure offers from Google, Amazon, Microsoft, Automall, and many more within three months of applying the strategy. Hi, my name is Messy Mungle and if you don't already know me, I'm a software engineer at Google and I created a lot of tech career advice content on Instagram, LinkedIn, and now YouTube as well. So make sure to hit the subscribe button and follow my other pages as well. So the number one thing that people get stuck on is what programming language do you use for an interview? Now usually programming languages don't matter, especially for fan companies. So unless you're applying for a specific role that requires you to interview in a specific language, choose whatever language that you are comfortable using. Now I say this with a little grain of salt because I actually failed one of my interviews because I was using C++ and I know this language executes faster than most other languages. However, I got rejected just because of the sheer amount of lines of code I had to write which could have been done in basically five to 10 lines of code if I was to use Python. So really what matters is the speed of which you program in and how quickly you're able to solve the problem. So my advice for you when you're choosing a programming language is actually to first look at that question. If it's a string related question where you have to take an input from the stream and then output it, etc, etc, just use the language like Python. It's much faster than using a language like C++ which requires you to add additional lines of code just to process that data. But generally speaking, choosing a programming language does not matter. Next let's talk about time complexity and space complexity. I do not care what phase of engineering you're in. If you're an intern, if you're looking for a new grad, if you're looking for senior engineering roles, time and space complexity is going to be asked. You should really know all of your own notations. It's actually this chart that I always use before going into any interview. You should always be able to look at your code and figure out what the space and time complexity of your algorithm is. This is definitely definitely going to be asked if you're an intern or a new grad, but even for senior engineering roles, sometimes it's asked. Now before I dive into the exact lead code strategy that I took, I want to talk about DSA fundamentals. If you don't know your DSA fundamentals, you're not going to be efficient with lead code. In fact, many of the interviews that I've taken in the past have asked me the most basic question that I learned back in like second year of college. For example, one of my interview questions in a top company was to implement a hash map and another one was to implement LRU cache. So this is why I say to make sure that you know your DSA fundamentals because you don't know when these questions could be asked. And the other thing is if you know your fundamentals very well, then you're going to be able to choose the correct data structure or algorithm that's required in order to solve a lead code problem. Now let's finally move on to the exact lead code strategy I used in order to crack all these fake companies. Number one, I suggest you get lead code premium or at least the CTC I've bought. I don't think lead code premium is required when you're just starting off, but if you're within one to two month mark of your interviews, I highly recommend getting the lead code premium so that you can solve the most frequently asked company questions. And I truly think that CTC I book is very good to have just again to brush over your fundamentals and kind of review the answers and how you go about thinking them in the first place. Now the exact strategy that I took is that number one, you want to go over arrays, link list and maps. Now obviously, first of all, you want to make sure that you understand what these data structures are and exactly why you use them. So it doesn't exactly matter how many questions you do for each of these categories, but you need to be able to figure out what wording each of these questions are using that kind of direct you to a specific data structure or algorithm. So after you do arrays, link list and map, I would move on to searching algorithms, sorting algorithms and trees. When you're an intern, most of the questions you're going to be asked is going to be within these first two categories. So you want to make sure that you're super, super good at these. You want to know your pre in and post-order traversals for the binary trees. And then for the searching and sorting algorithms, you want to know how to implement them, especially your binary search, linear search and quick sorts. And also again, know the time complexity and space complexity of these algorithms, especially when you apply them in a problem. Now moving on after you've done a couple of questions in these categories, you want to do one through 50 on link code in order. I think these questions give you a pretty good understanding of how to apply these algorithms as well as data structures before moving on to the more complex ones. Now the second part of this roadmap is really for your new grads and senior engineering roles. You're most likely not going to be asked link list type of questions, but still make sure that you know about these. Instead, what you want to focus on is graphs, backtracking algorithms, recursion, heaps and priority queues, especially when you're applying to FANG. There's a lot of different sorts of problems that is going to use at least one, if not two of these different data structures and algorithms. And these questions can be complex. So you really want to make sure that you know how to combine these things together. And if you do blind 75 or blind 150 next, depending on how much time you have, I think you're going to have a solid basic understanding of what these bigger companies require. What you want to focus on next is DP, tries and union sets. I know DP is everyone's favorite and I know it's very difficult. So most of the time you're probably not going to be asked DP problems, but you never know. So you want to at least practice 20, 30 questions of these before kind of giving up. I think tries and union sets are very good structures to know as well. Once you kind of say that to an interviewer, they're going to be very impressed that you thought of these data structures. So it's going to give you brownie points, but these are definitely the structures and algorithms that you want to learn at the very end when you're already good at your medium and hard level problems. Now finally, I want to address what to do when you're stuck in the middle of a tech interview. Obviously, the first thing is make sure you're getting the brute force solution out. But while you're doing that, make sure that you're thinking of what other data structure algorithm you can use to make your solution better. Cause that's a hundred percent going to be the follow up question. If you have time left. Second thing is make sure you're asking your clarification questions upfront and kind of making sure that you and your interviewer are on the same page. You don't want to be going down the wrong path and figure out that you're on the wrong path 20 to 30 minutes later in your interview. So really ask upfront, does this make sense to you? And if you're genuinely stuck in the interview, just ask for a hint. I think the worst thing for an interviewer is if you give up on a problem. Remember that an interviewer has been in the same exact seat that you are in currently. So really they want to try to help you. It's just that you need to ask for it and ask for it correctly. The interviewer is just trying to make sure that you're a person that they can work with. They're not trying to reject you. If you liked this video, then make sure to give it a thumbs up and make sure to subscribe to my channel below. Let me help you achieve your tech career dreams."

In [ ]:
# query = "what are the 9 habits"
# query = "query: " + query

# query_embedding = model.encode(query,normalize_embeddings=True,convert_to_tensor = True)

# query_embedding

In [ ]:
from sentence_transformers import util
# dot_scores = util.dot_score(a = query_embedding,b = embeddings_torch)[0]

In [ ]:
# top_k_result = torch.topk(dot_scores , k = 3)

In [ ]:
# top_k_result

In [ ]:
# transcript_data_after_chunking_together.iloc[3]['text']

In [ ]:
# top_k_result_numpy = top_k_result.indices.cpu().numpy()

In [ ]:
# content = "Based on the following context items, please answer the query. Give yourself room to think by extracting relevant passages from the context before answering the query. Dont return the thinking, only return the answer. Make sure your answers are as explanatory as possible." # Initialize before the loop
# for i, index in enumerate(top_k_result_numpy):
#     content += f"content {i}: " + transcript_data_after_chunking_together.iloc[index]['text'] + "start time : "+ str(transcript_data_after_chunking_together.iloc[index]['start'])+'\n'


# content += f"\n" + "answer the query based on the context provided in max 200 words use the start time whenever possible" + '\n' + query

# print(content)

In [ ]:
# def generate_query(user_input){
#     query = "query: " + user_input

#     query_embedding = model.encode(query,normalize_embeddings=True,convert_to_tensor = True)
#     dot_scores = util.dot_score(a = query_embedding,b = embeddings_torch)[0]
#     top_k_result = torch.topk(dot_scores , k = 3)
#     top_k_result_numpy = top_k_result.indices.cpu().numpy()
#     content = "Based on the following context items, please answer the query. Give yourself room to think by extracting relevant passages from the context before answering the query. Dont return the thinking, only return the answer. Make sure your answers are as explanatory as possible." # Initialize before the loop
#     for i, index in enumerate(top_k_result_numpy):
#         content += f"content {i}: " + transcript_data_after_chunking_together.iloc[index]['text'] + "start time : "+ str(transcript_data_after_chunking_together.iloc[index]['start'])+'\n'
#     content += f"\n" + "answer the query based on the context provided in max 200 words use the start time whenever possible" + '\n' + query

# }

def generate_query(user_input):
    query = "query: " + user_input
    content = ""
    query_embedding = model.encode(query, normalize_embeddings=True, convert_to_tensor=True)
    dot_scores = util.dot_score(a=query_embedding, b=embeddings_torch)[0]
    top_k_result = torch.topk(dot_scores, k=3)
    top_k_indices = top_k_result.indices.cpu().numpy()

    for i, index in enumerate(top_k_indices):

        row = transcript_data_after_chunking_together.iloc[index]
        content += f"content {i}: {row['text']} start time: {row['start']}\n"

    content += (
        "\nAnswer the query based on the context provided in max 200 words. "
        "Use the start time whenever possible\n"
        f"{query}"
    )

    return content

In [ ]:
! pip install google-generativeai

Requirement already satisfied: google-generativeai in /usr/local/lib/python3.11/dist-packages (0.8.5)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.25.1)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.176.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.38.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.11.7)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.14.1)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai) (1.70.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (0.4.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.73.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.7.14)

In [ ]:
import google.generativeai as genai


# client = genai.Client(api_key="AIzaSyChJavhK_2q-3x4c1accRKfiUM9c_xvR1c")
genai.configure(api_key=("AIzaSyDuHc9QbDs6VwpuqiRR6vbkpIi35AvtUz4"))

generation_config = {
  "temperature": 0,
  "top_p": 0.95,
  "top_k": 64,
  "max_output_tokens": 300,
  "response_mime_type": "text/plain",
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_NONE",
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE",
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE",
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE",
  },
]

instruction = """
You are a structured note-generation assistant built into a productivity app called YouNote.

Your task is to take in transcribed content from long-form sources (YouTube videos, playlists, lectures, or podcasts) and generate clear, concise, and well-structured notes.

Your notes must:
- Use bullet points, headings, and subheadings for readability.
- Extract key concepts, ideas, and facts — no fluff.
- Be written in plain, easy-to-understand language for students and self-learners.
- Preserve the original context and intent of the speaker.
- If the video is a tutorial, highlight steps, code patterns, or tools.
- If the video is theoretical, summarize definitions, examples, and logic flows.
- Avoid repetition or hallucinated content.
- Limit summary to what's present in the actual transcript chunks.

You're part of a multi-step map-reduce summarization system. Each chunk you get may be part of a larger video — so be precise and context-aware, but don’t assume outside knowledge.

Format the output as Markdown-compatible text.
"""

genai_model = genai.GenerativeModel(
  model_name="gemini-2.0-flash",
  safety_settings=safety_settings,
  generation_config=generation_config,
  system_instruction=instruction,
)

# response = client.models.generate_content(
#     model="", contents=content
# )
# print(response.text)

chat_session = genai_model.start_chat(
    history=[]
)

while True:

    user_input = input("You: ")
    print()

    user_input = generate_query(user_input)
    response = chat_session.send_message(user_input)

    model_response = response.text

    print(f'Bot: {model_response}')
    print()


    chat_session.history.append({"role": "user", "parts": [user_input]})
    chat_session.history.append({"role": "model", "parts": [model_response]})

You: whats the video about

Bot: Here's a summary of the video's content, based on the provided chunks:

*   **Advanced Data Structures and Algorithms:** These are good for brownie points, but should be learned after mastering medium and hard-level problems (0:00).
*   **Handling Tech Interview Stalls:**
    *   First, provide a brute-force solution while considering better data structures/algorithms.
    *   Ask clarifying questions upfront to ensure alignment with the interviewer.
    *   If genuinely stuck, ask for a hint. Interviewers want to help and see if you're someone they can work with (0:00).
*   **Time and Space Complexity:** Understanding Big O notation is crucial for all engineering levels. Be able to determine the time and space complexity of your code (1:35).
*   **DSA Fundamentals:** Strong fundamentals are essential for efficient LeetCode practice. Basic questions like implementing a hash map or LRU cache can be asked in interviews (1:44).

You: what do you think about faang companies

Bot: Here's what the provided content suggests about FAANG companies:

*   **Focus for New Grads/Senior Roles:** When applying to FAANG, prioritize graphs, backtracking algorithms, recursion, heaps, and priority queues (2:66). These companies often use problems that combine these data structures and algorithms.
*   **Language Choice:** Programming language generally doesn't matter for FAANG interviews unless a specific language is required for the role (0:00).
*   **Author's Success:** The speaker secured offers from Google, Amazon, and Microsoft by using the LeetCode strategy they discuss (2:66).

KeyboardInterrupt: Interrupted by user